<a href="https://colab.research.google.com/github/Visualizacao-Dados-BI-T3/mod2-visualizacao-dados/blob/main/ml_e_vieses/tecnicas_anonimizacao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd

# Dados mocados conforme solicitado
dados = {
    "id": [1, 2, 3, 4, 5],
    "email": [
        "joao.silva@email.com",
        "maria.souza@email.com",
        "carlos.oliveira@email.com",
        "ana.santos@email.com",
        "lucas.lima@email.com"
    ],
    "telefone": [
        "(11) 98765-4321",
        "(21) 97654-3210",
        "(31) 96543-2109",
        "(41) 95432-1098",
        "(51) 94321-0987"
    ],
    "cidade": [
        "São Paulo",
        "Rio de Janeiro",
        "Belo Horizonte",
        "Curitiba",
        "Porto Alegre"
    ],
    "produto": [
        "Smartphone",
        "Notebook",
        "Fone de Ouvido",
        "Monitor",
        "Teclado Mecânico"
    ],
    "valor": [1500.00, 3500.00, 150.00, 800.00, 250.00]
}

# Criando o DataFrame
df = pd.DataFrame(dados)

# Exibindo a tabela
df

,id,email,telefone,cidade,produto,valor
0,1,joao.silva@email.com,(11) 98765-4321,São Paulo,Smartphone,1500.0
1,2,maria.souza@email.com,(21) 97654-3210,Rio de Janeiro,Notebook,3500.0
2,3,carlos.oliveira@email.com,(31) 96543-2109,Belo Horizonte,Fone de Ouvido,150.0
3,4,ana.santos@email.com,(41) 95432-1098,Curitiba,Monitor,800.0
4,5,lucas.lima@email.com,(51) 94321-0987,Porto Alegre,Teclado Mecânico,250.0

Minimizando

In [2]:
analise = df[["cidade", "produto", "valor"]].copy()
analise

           cidade           produto   valor
0       São Paulo        Smartphone  1500.0
1  Rio de Janeiro          Notebook  3500.0
2  Belo Horizonte    Fone de Ouvido   150.0
3        Curitiba           Monitor   800.0
4    Porto Alegre  Teclado Mecânico   250.0

In [3]:
df

,id,email,telefone,cidade,produto,valor
0,1,joao.silva@email.com,(11) 98765-4321,São Paulo,Smartphone,1500.0
1,2,maria.souza@email.com,(21) 97654-3210,Rio de Janeiro,Notebook,3500.0
2,3,carlos.oliveira@email.com,(31) 96543-2109,Belo Horizonte,Fone de Ouvido,150.0
3,4,ana.santos@email.com,(41) 95432-1098,Curitiba,Monitor,800.0
4,5,lucas.lima@email.com,(51) 94321-0987,Porto Alegre,Teclado Mecânico,250.0

Supressão

In [5]:
sem_dados_pessoais = df.drop(columns=["id", "email", "telefone"]).copy()
sem_dados_pessoais

           cidade           produto   valor
0       São Paulo        Smartphone  1500.0
1  Rio de Janeiro          Notebook  3500.0
2  Belo Horizonte    Fone de Ouvido   150.0
3        Curitiba           Monitor   800.0
4    Porto Alegre  Teclado Mecânico   250.0

Máscara

In [9]:
mascarada = df[["telefone"]].copy()

mascarada["telefone"] = "***" + mascarada["telefone"].str[-4:]

mascarada

  telefone
0  ***4321
1  ***3210
2  ***2109
3  ***1098
4  ***0987

In [11]:
import pandas as pd

# Dados mocados incluindo a coluna idade
dados_com_idade = {
    "id": [1, 2, 3, 4, 5],
    "email": [
        "joao.silva@email.com",
        "maria.souza@email.com",
        "carlos.oliveira@email.com",
        "ana.santos@email.com",
        "lucas.lima@email.com"
    ],
    "telefone": [
        "(11) 98765-4321",
        "(21) 97654-3210",
        "(31) 96543-2109",
        "(41) 95432-1098",
        "(51) 94321-0987"
    ],
    "idade": [28, 35, 42, 19, 50],
    "cidade": [
        "São Paulo",
        "Rio de Janeiro",
        "Belo Horizonte",
        "Curitiba",
        "Porto Alegre"
    ],
    "produto": [
        "Smartphone",
        "Notebook",
        "Fone de Ouvido",
        "Monitor",
        "Teclado Mecânico"
    ],
    "valor": [1500.00, 3500.00, 150.00, 800.00, 250.00]
}

# Criando o DataFrame atualizado
df_completo = pd.DataFrame(dados_com_idade)

# Exibindo a nova tabela
df_completo

,id,email,telefone,idade,cidade,produto,valor
0,1,joao.silva@email.com,(11) 98765-4321,28,São Paulo,Smartphone,1500.0
1,2,maria.souza@email.com,(21) 97654-3210,35,Rio de Janeiro,Notebook,3500.0
2,3,carlos.oliveira@email.com,(31) 96543-2109,42,Belo Horizonte,Fone de Ouvido,150.0
3,4,ana.santos@email.com,(41) 95432-1098,19,Curitiba,Monitor,800.0
4,5,lucas.lima@email.com,(51) 94321-0987,50,Porto Alegre,Teclado Mecânico,250.0

Generalização

In [18]:
idade_mascarada = df_completo.copy()

# Ajustando os limites (bins) para coincidir com a quantidade de labels
idade_mascarada["faixa_etaria"] = pd.cut(idade_mascarada["idade"],
                                         bins=[0, 20, 30, 40, 50, 60, 70],
                                         labels=["0-19", "20-29", "30-39", "40-49", "50-59", "60-69"],
                                         right=False)

idade_mascarada

,id,email,telefone,idade,cidade,produto,valor,faixa_etaria
0,1,joao.silva@email.com,(11) 98765-4321,28,São Paulo,Smartphone,1500.0,20-29
1,2,maria.souza@email.com,(21) 97654-3210,35,Rio de Janeiro,Notebook,3500.0,30-39
2,3,carlos.oliveira@email.com,(31) 96543-2109,42,Belo Horizonte,Fone de Ouvido,150.0,40-49
3,4,ana.santos@email.com,(41) 95432-1098,19,Curitiba,Monitor,800.0,0-19
4,5,lucas.lima@email.com,(51) 94321-0987,50,Porto Alegre,Teclado Mecânico,250.0,50-59

Agregação

In [21]:
resumo = (
    df_completo.groupby("cidade", as_index=False)
    .agg(pessoas=("id", "nunique"),
         valor_medio=("valor", "mean"),
         valor_total=("valor", "sum"))
)
display(resumo)

           cidade  pessoas  valor_medio  valor_total
0  Belo Horizonte        1        150.0        150.0
1        Curitiba        1        800.0        800.0
2    Porto Alegre        1        250.0        250.0
3  Rio de Janeiro        1       3500.0       3500.0
4       São Paulo        1       1500.0       1500.0

Perturbação

In [22]:
import numpy as np

rng = np.random.default_rng(42)

perturbada = df_completo[["cidade", "valor"]].copy()
perturbada["valor"] = (
    perturbada["valor"] + rng.normal(0, 10, len(perturbada))
).round(2)
# Lado a lado somente para ensinar com dados fictícios.
comparacao = pd.DataFrame({
    "original": df_completo["valor"],
    "com_ruido": perturbada["valor"]
})
display(comparacao.head())
print("Média original:", round(df_completo["valor"].mean(), 2))
print("Média alterada:", round(perturbada["valor"].mean(), 2))

   original  com_ruido
0    1500.0    1503.05
1    3500.0    3489.60
2     150.0     157.50
3     800.0     809.41
4     250.0     230.49

Média original: 1240.0
Média alterada: 1238.01

Pseudoanonimização

In [23]:
import uuid
associacao_restrita = df_completo[["id"]].copy()
associacao_restrita["codigo"] = [uuid.uuid4().hex for _ in range(len(df_completo))]

pseudonimizada = (
    df_completo.merge(associacao_restrita, on="id", validate="one_to_one")
    [["codigo", "cidade", "produto", "valor"]].copy()
)
display(pseudonimizada.head())
print("Tabela de associação existe:", not associacao_restrita.empty)
# Não exibimos a associação. Ela ainda existe na memória deste notebook.

                             codigo          cidade           produto   valor
0  46918838acf346db9d7ec2e957775aeb       São Paulo        Smartphone  1500.0
1  ec5cd6e23baf4e319b62a993bb41c794  Rio de Janeiro          Notebook  3500.0
2  50dd3386e43b442f82bf7e22bf02e30c  Belo Horizonte    Fone de Ouvido   150.0
3  740cfb8593b74a868ee66cf4eb800dd9        Curitiba           Monitor   800.0
4  76929f84e8cf4d39a57dbe1fbb27f611    Porto Alegre  Teclado Mecânico   250.0

Tabela de associação existe: True

k-anonimato

In [38]:
quase_identificadores = ["cidade", "faixa_etaria"]
contagens = (
    idade_mascarada.groupby(quase_identificadores, observed=True, dropna=False)
    .size().reset_index(name="pessoas_no_grupo")
)
k = 3
display(contagens)
display(contagens[contagens["pessoas_no_grupo"] < k])
print("Menor grupo nesse recorte:", contagens["pessoas_no_grupo"].min())

           cidade faixa_etaria  pessoas_no_grupo
0  Belo Horizonte        40-49                 1
1        Curitiba         0-19                 1
2    Porto Alegre        50-59                 1
3  Rio de Janeiro        30-39                 1
4       São Paulo        20-29                 1

           cidade faixa_etaria  pessoas_no_grupo
0  Belo Horizonte        40-49                 1
1        Curitiba         0-19                 1
2    Porto Alegre        50-59                 1
3  Rio de Janeiro        30-39                 1
4       São Paulo        20-29                 1

Menor grupo nesse recorte: 1

In [39]:
saida_quase_identificadores = (
    idade_mascarada[quase_identificadores]
    .merge(contagens, on=quase_identificadores, validate="many_to_one")
)
saida_quase_identificadores = saida_quase_identificadores.loc[
    saida_quase_identificadores["pessoas_no_grupo"] >= k,
    quase_identificadores
].copy()
display(saida_quase_identificadores)
print("Registros retidos:", len(saida_quase_identificadores))

Empty DataFrame
Columns: [cidade, faixa_etaria]
Index: []

Registros retidos: 0

In [24]:
import pandas as pd
from IPython.display import display

amostra = pd.DataFrame({
    "pessoa_id": [f"A{i:03}" for i in range(1, 25)],
    "nome": [f"Aluno fictício {i}" for i in range(1, 25)],
    "email": [f"aluno{i}@example.invalid" for i in range(1, 25)],
    "idade": [23, 27, 31, 35, 41, 45] * 4,
    "regiao": ["Centro"] * 18 + ["Periferia"] * 6,
    "modalidade": ["Online"] * 16 + ["Presencial"] * 2
                  + ["Online"] * 2 + ["Presencial"] * 4,
    "canal_resposta": ["Aplicativo"] * 16 + ["Balcão"] * 2
                     + ["Aplicativo"] * 2 + ["Balcão"] * 4,
    "informacao_saude": ["Relato fictício de saúde"] * 24,
    "matriculou": [True] * 24,
    "concluiu": [True] * 14 + [False] * 4
                + [True] * 2 + [False] * 4,
    "consentiu_ofertas": [True, False, True, False, True, False] * 4,
    "revogou_ofertas": [False] * 23 + [True]
})

display(amostra.head())

,pessoa_id,nome,email,idade,regiao,modalidade,canal_resposta,informacao_saude,matriculou,concluiu,consentiu_ofertas,revogou_ofertas
0,A001,Aluno fictício 1,aluno1@example.invalid,23,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
1,A002,Aluno fictício 2,aluno2@example.invalid,27,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
2,A003,Aluno fictício 3,aluno3@example.invalid,31,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
3,A004,Aluno fictício 4,aluno4@example.invalid,35,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
4,A005,Aluno fictício 5,aluno5@example.invalid,41,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False

In [25]:
amostra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pessoa_id          24 non-null     object
 1   nome               24 non-null     object
 2   email              24 non-null     object
 3   idade              24 non-null     int64
 4   regiao             24 non-null     object
 5   modalidade         24 non-null     object
 6   canal_resposta     24 non-null     object
 7   informacao_saude   24 non-null     object
 8   matriculou         24 non-null     bool
 9   concluiu           24 non-null     bool
 10  consentiu_ofertas  24 non-null     bool
 11  revogou_ofertas    24 non-null     bool
dtypes: bool(4), int64(1), object(7)
memory usage: 1.7+ KB

Resposta da atividade

C1. Crie base_minima com identificador interno, região, modalidade, matrícula e conclusão. O identificador ajuda a contar pessoas na análise interna, mas não precisa aparecer no resumo final.

In [26]:
amostra.columns

Index(['pessoa_id', 'nome', 'email', 'idade', 'regiao', 'modalidade',
       'canal_resposta', 'informacao_saude', 'matriculou', 'concluiu',
       'consentiu_ofertas', 'revogou_ofertas'],
      dtype='object')

In [28]:
base_minima = amostra[["pessoa_id", "regiao", "modalidade", "matriculou", "concluiu"]].copy()
base_minima

   pessoa_id     regiao  modalidade  matriculou  concluiu
0       A001     Centro      Online        True      True
1       A002     Centro      Online        True      True
2       A003     Centro      Online        True      True
3       A004     Centro      Online        True      True
4       A005     Centro      Online        True      True
5       A006     Centro      Online        True      True
6       A007     Centro      Online        True      True
7       A008     Centro      Online        True      True
8       A009     Centro      Online        True      True
9       A010     Centro      Online        True      True
10      A011     Centro      Online        True      True
11      A012     Centro      Online        True      True
12      A013     Centro      Online        True      True
13      A014     Centro      Online        True      True
14      A015     Centro      Online        True     False
15      A016     Centro      Online        True     False
16      A017     Centro  Presencial        True     False
17      A018     Centro  Presencial        True     False
18      A019  Periferia      Online        True      True
19      A020  Periferia      Online        True      True
20      A021  Periferia  Presencial        True     False
21      A022  Periferia  Presencial        True     False
22      A023  Periferia  Presencial        True     False
23      A024  Periferia  Presencial        True     False

C2. Agrupe por região e modalidade. Conte pessoas distintas e conclusões. Como existe uma pessoa por linha, a soma dos booleanos de conclusão conta concluintes.

In [29]:
resumo = base_minima.groupby(["regiao", "modalidade"]).agg(
    pessoas=("pessoa_id", "nunique"),
    conclusoes=("concluiu", "sum")
)

resumo

                      pessoas  conclusoes
regiao    modalidade
Centro    Online           16          14
          Presencial        2           0
Periferia Online            2           2
          Presencial        4           0

C3. Calcule o percentual de conclusão. O denominador deve ser o número de pessoas matriculadas representadas no recorte; nesta amostra todas estão matriculadas.

In [30]:
resumo["% conclusão"] = 100 * (resumo["conclusoes"] / resumo['pessoas'])

resumo

                      pessoas  conclusoes  % conclusão
regiao    modalidade
Centro    Online           16          14         87.5
          Presencial        2           0          0.0
Periferia Online            2           2        100.0
          Presencial        4           0          0.0

C4. Localize grupos com menos de três pessoas. Use três apenas como alerta didático, não como garantia de anonimização ou exigência da LGPD.

In [31]:
grupos_menor_que_tres = resumo.loc[resumo['pessoas'] < 3]
grupos_menor_que_tres

                      pessoas  conclusoes  % conclusão
regiao    modalidade
Centro    Presencial        2           0          0.0
Periferia Online            2           2        100.0

In [32]:
grupo_maior_que_tres = resumo.loc[resumo['pessoas'] >= 3]
grupo_maior_que_tres

                      pessoas  conclusoes  % conclusão
regiao    modalidade
Centro    Online           16          14         87.5
Periferia Presencial        4           0          0.0

C5. Prepare uma versão que omita os grupos pequenos e descreva riscos que ainda precisam ser avaliados antes de publicar.

In [33]:
amostra

,pessoa_id,nome,email,idade,regiao,modalidade,canal_resposta,informacao_saude,matriculou,concluiu,consentiu_ofertas,revogou_ofertas
0,A001,Aluno fictício 1,aluno1@example.invalid,23,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
1,A002,Aluno fictício 2,aluno2@example.invalid,27,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
2,A003,Aluno fictício 3,aluno3@example.invalid,31,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
3,A004,Aluno fictício 4,aluno4@example.invalid,35,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
4,A005,Aluno fictício 5,aluno5@example.invalid,41,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
5,A006,Aluno fictício 6,aluno6@example.invalid,45,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
6,A007,Aluno fictício 7,aluno7@example.invalid,23,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
7,A008,Aluno fictício 8,aluno8@example.invalid,27,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
8,A009,Aluno fictício 9,aluno9@example.invalid,31,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
9,A010,Aluno fictício 10,aluno10@example.invalid,35,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
10,A011,Aluno fictício 11,aluno11@example.invalid,41,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
11,A012,Aluno fictício 12,aluno12@example.invalid,45,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
12,A013,Aluno fictício 13,aluno13@example.invalid,23,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
13,A014,Aluno fictício 14,aluno14@example.invalid,27,Centro,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
14,A015,Aluno fictício 15,aluno15@example.invalid,31,Centro,Online,Aplicativo,Relato fictício de saúde,True,False,True,False
15,A016,Aluno fictício 16,aluno16@example.invalid,35,Centro,Online,Aplicativo,Relato fictício de saúde,True,False,False,False
16,A017,Aluno fictício 17,aluno17@example.invalid,41,Centro,Presencial,Balcão,Relato fictício de saúde,True,False,True,False
17,A018,Aluno fictício 18,aluno18@example.invalid,45,Centro,Presencial,Balcão,Relato fictício de saúde,True,False,False,False
18,A019,Aluno fictício 19,aluno19@example.invalid,23,Periferia,Online,Aplicativo,Relato fictício de saúde,True,True,True,False
19,A020,Aluno fictício 20,aluno20@example.invalid,27,Periferia,Online,Aplicativo,Relato fictício de saúde,True,True,False,False
20,A021,Aluno fictício 21,aluno21@example.invalid,31,Periferia,Presencial,Balcão,Relato fictício de saúde,True,False,True,False
21,A022,Aluno fictício 22,aluno22@example.invalid,35,Periferia,Presencial,Balcão,Relato fictício de saúde,True,False,False,False
22,A023,Aluno fictício 23,aluno23@example.invalid,41,Periferia,Presencial,Balcão,Relato fictício de saúde,True,False,True,False
23,A024,Aluno fictício 24,aluno24@example.invalid,45,Periferia,Presencial,Balcão,Relato fictício de saúde,True,False,False,True

In [35]:
amostra["canal_resposta"].value_counts()

canal_resposta
Aplicativo    18
Balcão         6
Name: count, dtype: int64

In [36]:
amostra["idade"].value_counts()

idade
23    4
27    4
31    4
35    4
41    4
45    4
Name: count, dtype: int64